data:
  template: rasp_thuerey_geopotential
  ds_format: zarr
  train_shuffle_chunks: True
  train_shuffle_in_chunks: True
  val_shuffle_chunks: False
  val_shuffle_in_chunks: False

setup:
  loss_fn_name: MSE_Loss

fourcastnet:
  lr_scheduler_name: CosineAnnealingLR
  batch_size: 64
  learning_rate: 0.0005
  num_workers: 2
  afno_net:
    patch_size: 2
    depth: 8
    embed_dim: 256
    num_blocks: 8
    drop_path_rate: 0.
    drop_rate: 0.
    mlp_ratio: 4.
    sparsity_threshold: 0.01
    hard_thresholding_fraction: 1.

training:
  max_steps: 5000000
  ema_decay: 0.9999
  limit_val_batches: 10
  accelerator: "cuda"
  devices: -1
  patience: 10