data:
  template: rasp_thuerey_geopotential
  ds_format: zarr
  train_shuffle_chunks: True
  train_shuffle_in_chunks: True
  val_shuffle_chunks: False
  val_shuffle_in_chunks: False

training:
  max_steps: 5000000
  ema_decay: 0.9999
  limit_val_batches: 10
  accelerator: "cuda"
  devices: -1
  patience: 50
  
model:
  loss_fn_name: MSE_Loss
  sampler_name: DDPM
  lr_scheduler_name: ReduceLROnPlateau
  batch_size: 128
  learning_rate: 0.00005
  num_workers: 2

  diffusion:
    num_diffusion_steps_inference: 200
    sampler_name: DDPM
    denoising_diffusion_process:
      unet_type: UnetConvNextBlock
      noise_schedule: linear
      use_cyclical_padding: False
      num_diffusion_steps: 1000
      dims_mults: [1,2,4,8]
      num_channels_base: 128

  forecast:
    AFNO:
      patch_size: 2
      depth: 8
      embed_dim: 128
      num_blocks: 8
      drop_path_rate: 0.
      drop_rate: 0.
      mlp_ratio: 4.
      sparsity_threshold: 0.01
      hard_thresholding_fraction: 1.
      final_act: null