data:
  template: rasp_thuerey_geopotential_highres
  ds_format: zarr
  train_shuffle_chunks: True
  train_shuffle_in_chunks: True
  val_shuffle_chunks: False
  val_shuffle_in_chunks: False

vae:
  dim: null
  type: output
  beta: 0.001
  batch_size: 128
  lr: 0.001
  lr_scheduler_name: ReduceLROnPlateau
  num_workers: 1
  channel_mult: [1,1]

training:
  max_steps: 50000000
  ema_decay: 0.9999
  limit_val_batches: 10
  accelerator: "cuda"
  devices: -1