data_specs:
  conditioning_time_step: [0]
  max_chunksize: 0.5  # maximal size per chunk in GB
  conditioning_vars:
    # fields with pressure levels
    temperature:
      level: [850]
  # constant input fields
  constants:
    - orography
    - lat2d
    - lsm
  delta_t: 6
  lead_time: 1 # 3 days (3 times 4 times 6 hours)
  output_vars:  # same as conditioning variables
    # fields with pressure levels
    temperature:
      level: [850]
  spatial_resolution: 5.625deg
exp_data:
  test:
    start: 2017-01-01 00:00:00
    end: 2018-12-31 00:00:00
  train:
    start: 1979-01-02 00:00:00
    end: 2015-12-31 00:00:00
  val:
    start: 2016-01-01 00:00:00
    end: 2016-12-31 00:00:00

