data_specs:
  conditioning_time_step: [0, -1, -2]
  max_chunksize: 0.5  # maximal size per chunk in GB
  conditioning_vars:
    # fields with pressure levels
    temperature:
      level: [50, 250, 500, 600, 700, 850, 925]
    geopotential:
      level: [50, 250, 500, 600, 700, 850, 925]
    u_component_of_wind:
      level: [50, 250, 500, 600, 700, 850, 925]
    v_component_of_wind:
      level: [50, 250, 500, 600, 700, 850, 925]
    specific_humidity:
      level: [50, 250, 500, 600, 700, 850, 925]
    # 2d fields:
    2m_temperature:
      level:
    total_precipitation:
      level:
    toa_incident_solar_radiation:
      level:
  # constant input fields
  constants:
    - orography
    - lat2d
    - lsm
  delta_t: 6
  lead_time: 12 # 3 days (3 times 4 times 6 hours)
  output_vars:
    # 2d fields:
    temperature:
      level: [850,]
  spatial_resolution: 2.8125deg
exp_data:
  test:
    start: 2017-01-01 00:00:00
    end: 2018-12-31 00:00:00
  train:
    start: 1979-01-02 00:00:00
    end: 2015-12-31 00:00:00
  val:
    start: 2016-01-01 00:00:00
    end: 2016-12-31 00:00:00

