data: 
  ds_format: zarr

batchsize: 128
shuffle_chunks: False
shuffle_in_chunks: False
sampler: null
loss_fn: null

hydra:
  job:
    chdir: False
  run:
    dir: ${paths.hydra_config_dir}/inference/${data.template}/${experiment}/${model_name}/${now:%Y-%m-%d_%H-%M-%S}