defaults:
  - paths: default_paths
  - _self_

batchsize: 128
shuffle_chunks: False
shuffle_in_chunks: False
sampler: null
loss_fn: null

hydra:
  job:
    chdir: False
  run:
    dir: ${paths.dir_HydraConfigs}/inference/${data.template}/${hydra.runtime.choices.experiment}/${model_name}/${now:%Y-%m-%d_%H-%M-%S}